alias gs="git status"
alias rs="rails server"
alias ga="git add"
alias gc="git commit -m"
alias gpo="git push origin"
alias be="bundle exec"
alias bi="bundle install"
alias gd="git diff"
alias gpl="git pull origin"
alias gl="git log"
alias gco="git checkout"
alias code="cd ~/code"
alias shutl="cd ~/code/shutl"
alias admin="cd ~/code/shutl/admin_portal"
alias gb="git branch"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:/usr/local/bin/npm:$PATH"
